### ISSUE TITLE
Improvement request. WebGL rendering.

### ISSUE THREAD

**Issue by henrikekblad** [mcous/svgerber#15]
Hi and thanks for a great project. Plan to use it on a site for sharing open hardware projects. 

Would be cool if you could add support for WebGL generating to enable user to inspect the drawing in 3-dimensions. 

mayhewlabs (http://mayhewlabs.com/3dpcb) has a javascript that does this using the excellent three-3d-library(http://threejs.org/). 

mayhewlabs example/code hasn't really been changed the last couple of years and doesn't seem to work with some of the gerber-files I feed it with. I guess you would make it more up-to-date in notime since you already parse the gerberfiles. :)

**Comment by mcous** [comment]
Deprecating this project in favor of http://viewer.tracespace.io. If you're still interested in this feature, feel free to re-open this issue at [tracespace/viewer](https://github.com/tracespace/viewer)!
