### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by apla** [mcous/svgerber#16]
```
Error: module "gerber-to-svg" not found from "/Users/apla/work/pcb/to-production/svgerber/src/workers/gerber-worker.coffee"
```

fixed with `npm install -g gerber-to-svg`

**Comment by mcous** [comment]
Opps, my bad. There was a series of bad deploys of gerber-to-svg between 0.2 and 0.3 (typo in my travis file... dumb mistake). I had this package.json update to bring in the latest gerber-to-svg sitting in my working directory and never pushed it.

Thanks for pointing this out; you should be good to go now.
