### ISSUE TITLE
Support unit conversion in board builder

### ISSUE THREAD

**Issue by kasbah** [mcous/svgerber#18]
Hey, thanks for this site! I am trying to render the [MC HCK board](https://github.com/mchck/mchck-board) using [these gerbers](http://kaspar.h1x.com/mchck-gerbers.zip). The layers all seem to be detected and rendered individually but the composite top and bottom views don't show up.

**Comment by mcous** [comment]
Interesting, there seems to be something going wrong in the board builder due to the drill file. The board renders fine without it. I'll have to dig in a little to see what's going wrong.

**Comment by kasbah** [comment]
Thanks for taking a look. I played around a little with the drill file plotting options and found that switching units from inches (the default in KiCad) to millimetres fixes it!

**Comment by mcous** [comment]
Oh, I see, the drill file is in inches and the gerbers are in mm. The board builder [doesn't like it when the units don't match](https://github.com/mcous/svgerber/blob/master/src/build-board.coffee#L60).

I've got a newer board builder that I've been spending some time on (and could potentially account for unit differences); maybe this is a sign I need to get it deployed hah

**Comment by kasbah** [comment]
Yes, I think the differing units will happen in KiCad currently if you work in mm and don't touch the drill plotting options, which I suspect happens quite often.

**Comment by mcous** [comment]
More recently I was running into a problem where the OSX KiCad builds could only output drill files in mm with high precision, which probably means I also need to tackle [this issue in the conversion library](https://github.com/mcous/gerber-to-svg/issues/16).

As for outline problems, I'd like them if you've got them. The new builder is a lot more robust in this regard, and is actually properly unit tested. The main issue I fixed was related to outline files that had more than tool, often for text or something. But if you've seen issues I haven't run into yet I can build them into tests and everyone wins.

**Comment by mcous** [comment]
tracespace/pcb-stackup and http://viewer.tracespace.io support automatic scaling based on units!
