### ISSUE TITLE
TypeError: i.matches is not a function

### ISSUE THREAD

**Issue by kasbah** [mcous/svgerber#19]
This is when running my own instance. The gerbers don't render and this error comes from `vendor.js 62:11065`. I tried restricting lodash stuff to `2.4.1` exactly but that didn't seem to help.

**Comment by mcous** [comment]
I'm seeing the same error with a fresh clone. I've got a working one as well, so I'll find which versions of backbone, lodash, and jquery it's running and see if locking them helps.

**Comment by mcous** [comment]
Pinned the dependencies and it's fixing things on my end. Although I seem to have broken icons, so I'll reopen until that's fixed. Let me know how it goes for you.

**Comment by mcous** [comment]
Ok this should be good to go. Wipe out your `node_modules` folder and run `$ npm install` and let me know how it goes.
