### ISSUE TITLE
Mask overlapping outlines is not removed in board view

### ISSUE THREAD

**Issue by kasbah** [mcous/svgerber#20]
The [Bus Pirate v3.6 gerbers](http://kaspar.h1x.com/bus-pirate-gerbers.zip) are a good example. The edges are rounded but the mask just keeps going.

[![](https://i.imgur.com/vLHG7nv.png)](http://kaspar.h1x.com/bus-pirate-gerbers.zip)

**Comment by mcous** [comment]
So this is an interesting problem, because the board outline gerber has a tiny, 0.0001in gap in the outline (at lines 454 and 455 in BusPirate-v3.6-SSOP.gko).

The board shape feature works by building a graph of adjacent outline points and walking them in order to create a manifold shape that can be filled to mask the board. If it fails to find a manifold shape it will fall back to just drawing the board as a rectangle with the outline indicated by a line.

Neither the old builder or the new builder has any sort of gap repair functionality, although this certainly provides a good case for when it would be needed.

**Comment by kasbah** [comment]
I see (though I can't decipher the gerber format yet). There is a similar problem with the [MC HCK gerbers](http://kaspar.h1x.com/mchck-gerbers.zip) (now in mm!) and I have seen it on a few other boards as well so I think closing gaps would be really good.

[![](http://i.imgur.com/oaOAwj9.png)](http://kaspar.h1x.com/mchck-gerbers.zip)

**Comment by mcous** [comment]
I've looked at those MC HCK gerbers, and there's a slightly different problem with them: the outline is manifold, but it's drawn using three different tool sizes (line widths). The (new) outline builder splits shapes up by tool size for safety.

That being said, in this case the tool sizes are 0.1 mm, 0.0996mm, and 0.09906 mm, so I'm thinking by default the outline builder should combine tools that are within some size threshold, and also have an option to combine all tools.

With the tool sizes fixed up and run through new builder:
![test-top](https://cloud.githubusercontent.com/assets/2963448/7818920/8356d7ee-03ac-11e5-8066-0a568c8ad46d.png)

**Comment by kasbah** [comment]
>Neither the old builder or the new builder has any sort of gap repair functionality, although this certainly provides a good case for when it would be needed.

I looked into this a bit but I am really struggling. So the outline builder will crash on this (ith) `points` element because it's `segments` length is just one. Ok, but I am not quite sure how _it_ and it's surrounding points describe a small gap and how I would repair it

~~~js
i - 1:
{ x: 438.6,
  y: 617.6,
  segments: 
   [ { seg: 
        { start: 
           { x: 438.8,
             y: 609.9,
             segments: 
              [ { seg: [Object], rel: 'end' },
                { seg: [Circular], rel: 'start' },
                { seg: [Object], rel: 'end' },
                { seg: [Object], rel: 'start' } ] },
          end: [Circular] },
       rel: 'end' },
     { seg: 
        { start: [Circular],
          end: 
           { x: 438.8,
             y: 609.9,
             segments: 
              [ { seg: [Object], rel: 'end' },
                { seg: [Object], rel: 'start' },
                { seg: [Circular], rel: 'end' },
                { seg: [Object], rel: 'start' } ] } },
       rel: 'start' } ] } 
i:
{ x: 438.7,
  y: 617.6,
  segments: 
   [ { seg: 
        { start: [Circular],
          end: 
           { x: 438.7,
             y: 1759.3,
             segments: [ { seg: [Circular], rel: 'end' } ] } },
       rel: 'start' } ] } 
i + 1:
{ x: 438.7,
  y: 1759.3,
  segments: 
   [ { seg: 
        { start: 
           { x: 438.7,
             y: 617.6,
             segments: [ { seg: [Circular], rel: 'start' } ] },
          end: [Circular] },
       rel: 'end' } ] } 

~~~

**Comment by mcous** [comment]
So the gap is the fact that Point i-1 and Point i were created as separate points.

I haven't tried anything with this yet, but I think the key to gap filling will be [this line](https://github.com/mcous/svgerber/blob/master/src/build-board-outline.coffee#L69) and [this line](https://github.com/mcous/svgerber/blob/master/src/build-board-outline.coffee#L93) in build-board-outline.coffee. Those two lines are responsible for checking if a given point has been recorded already, and if they could be expanded to check not only points with the exact same coordinates but also coordinates within some tiny distance, we might be able to fix our problem.

**Comment by kasbah** [comment]
I had an incling that was it and did try this:

~~~diff
diff --git a/src/build-board-outline.coffee b/src/build-board-outline.coffee
index 5deed2d..26dc413 100644
--- a/src/build-board-outline.coffee
+++ b/src/build-board-outline.coffee
@@ -67,7 +69,10 @@ module.exports = (outline) ->
     if i >= outline.length then break
     else
       start = find points, { x: x, y: y }
-      if not start? then newStart = true; start = new Point x, y
+      if not start?
+        start = find points, (p) ->
+          Math.abs(p.x - x) <= 0.1 && Math.abs(p.y - y) <= 0.1
+        if not start? then newStart = true; start = new Point x, y
 
     # check our current character again to get the end of the segment
     if outline[i] is 'L'
@@ -91,7 +96,10 @@ module.exports = (outline) ->
       # set the path start if ncessary
       if not pathStart? then pathStart = start
       end = find points, { x: x, y: y }
-      if not end? then newEnd = true; end = new Point x, y
+      if not end?
+        end = find points, (p) ->
+          Math.abs(p.x - x) <= 0.1 && Math.abs(p.y - y) <= 0.1
+        if not end? then newEnd = true; end = new Point x, y
~~~

But that made the whole board disappear and trying it with a threshold of 0.01 still has the same `points`.

**Comment by mcous** [comment]
The whole board disappearing is interesting and sounds like you might be on the right track and hitting a different bug entirely. what does the board mechanical mask layer SVG look like?

**Comment by kasbah** [comment]
[This is the top.svg](http://kaspar.h1x.com/top.svg) and this is the `top-out_2` layer with the fills colors and stroke-widths changed:

![](http://kaspar.h1x.com/top-out_2.svg)
