### ISSUE TITLE
Compact menu doesn't trigger at 721px width

### ISSUE THREAD

**Issue by kasbah** [mcous/svgerber#22]
At least on my machine (font problem?) the compact menu should be triggered at 721px wide `window.innerWidth`.

![](http://i.imgur.com/MjcEYmS.png)

**Comment by mcous** [comment]
Hah damn. Mobile breakpoint is set [here](https://github.com/mcous/svgerber/blob/master/styles/index.styl#L29) to 43em, which I believe corresponds to 43 * 16px = 688px (although I'm super hazy on em, rem, and all that).

Want to find a better value and send me a PR? I've been in China on business for a week and a half now so I can't get to these things super quickly.
