### ISSUE TITLE
Create a chrome plugin/grease monkey/tamper monkey script to view gerbers in github

### ISSUE THREAD

**Issue by joeferner** [mcous/svgerber#25]
It would be neat if there was a plugin so that when ever you were on a github page like this https://github.com/mcous/svgerber/blob/master/samples/clockblock-hub-B_Cu.gbl you would be presented with the image instead of the raw text. Maybe add an additional button to the "Raw", "Blame", "History" to allow switching between them.

**Comment by mcous** [comment]
I agree! I'm working on a rewrite of the [gerber conversion library](https://github.com/mcous/gerber-to-svg) to handle streaming data (e.g. from a GET request). So I think once that's done this could be easier.

That being said, I've never written a Chrome Extension or Grease Monkey script, but it could be fun if I ever have free time. Got any interest in writing that tool? The other thought I had (that I started some very preliminary work on) was a opt-in site (ala Travis, David, etc) that hooked into pushes from GitHub and generated new renders for new files.

**Comment by kasbah** [comment]
Displaying _diffs_ would be really cool!

**Comment by mcous** [comment]
Right?? I know GitHub has SVG diffs built in, so it seems like a definite possibility

**Comment by mcous** [comment]
The svgerber project is now deprecated in favor of http://viewer.tracespace.io, and I'm likely never (or rather, effectively never) going to have time to work on this particular feature request, despite how cool I think it'd be.

If you're interested in building this yourself (or under the tracespace org), feel free to email or open issues over at mcous/gerber-to-svg and I'll do my best to help!
